### ISSUE TITLE
Add Linux wheels to https://pypi.org/project/perfmetrics/

### ISSUE THREAD

**Issue by ericof** [zodb/perfmetrics#22]
Trying to install the Linux wheel for Relstorage 3.0.0 fails because permetrics release 3.0.0 contains only wheels for Windows and Mac.

**Comment by jamadden** [comment]
Thanks for the report. manylinux binary wheels have been quite low priority for this package because most Linux users either already have a compiler or have the ability to easily install one, and this package doesn't have any exotic or complex dependencies and it compiles very quickly even on old compilers with no special settings. (RelStorage, in contrast, makes some specific demands of its compiler configuration.)

I'll probably get around to setting up the necessary infrastructure for this package someday, but it probably won't be today. I'll leave this here as a reminder.

In the meantime, I would suggest installing a compiler and the necessary Python development packages.

**Comment by ericof** [comment]
@jamadden Thank you for the quick response.
The use case I have is related to reusing a docker image that leaves no compiler available (https://hub.docker.com/r/plone/plone/tags).
I have a quick and dirty solution for now, but given the time I plan to send you a PR following the example from [pypa manylinux demo project](https://github.com/pypa/python-manylinux-demo).

**Comment by jamadden** [comment]
Wheels uploaded and release scripts updated.
